version: "2"

networks:
  web:
    external: true

services:
  shopware-php:
    extends:
      file: shopware.yml
      service: shopware-base-php

  shopware577:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-8.0
    links:
     - db
    environment:
      SWDB_DATABASE: shopware577
      SW_HOST: sweasycredit.shopware577.dev.netzkollektiv.com
      SW_DOWNLOAD_URL: https://www.shopware.com/de/Download/redirect/version/sw5/file/install_5.7.7_cba194ae2aab11d165a3876608a481bcbb971f57.zip
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware577.dev.netzkollektiv.com"

  shopware57:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-7.4
    links:
     - db
    environment:
      SWDB_DATABASE: shopware57
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware57.dev.netzkollektiv.com"

  shopware56:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-7.3
    links:
     - db
    environment:
      SWDB_DATABASE: shopware56
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware56.dev.netzkollektiv.com"

  shopware55:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-7.2
    links:
     - db
    environment:
      SWDB_DATABASE: shopware55
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware55.dev.netzkollektiv.com"

  shopware54:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-7.1
    links:
     - db
    environment:
      SWDB_DATABASE: shopware54
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware54.dev.netzkollektiv.com"

  shopware53:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-7.0
    links:
     - db
    environment:
      SWDB_DATABASE: shopware53
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware53.dev.netzkollektiv.com"

  shopware52:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-5.6
    links:
     - db
    environment:
      SWDB_DATABASE: shopware52
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware52.dev.netzkollektiv.com"

  shopware51:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-5.6
    links:
     - db
    environment:
      SWDB_DATABASE: shopware51
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware51.dev.netzkollektiv.com"

  shopware50:
    extends: shopware-php
    image: netzkollektivgmbh/docker-shopware:php-5.6
    links:
     - db
    environment:
      SWDB_DATABASE: shopware50
    labels:
      - "traefik.web.frontend.rule=Host: sweasycredit.shopware50.dev.netzkollektiv.com"

  docs:
    image: nginx
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.web.port=80'
      - 'traefik.docker.network=web'
      - "traefik.web.frontend.rule=Host: sweasycredit.docs.dev.netzkollektiv.com"
    networks:
      - web
      - default

  db:
    image: mysql:5.7
    ports:
      - "127.0.0.1:30360:3306"
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=shopware
    volumes:
      - ".db:/var/lib/mysql"
    networks:
      - default
