version: "2"
services: 
  shopware-base-php:
    image: netzkollektivgmbh/docker-shopware:php-7.3
    volumes:
      - ./src/Frontend/NetzkollektivEasyCredit:/var/www/html/engine/Shopware/Plugins/Local/Frontend/NetzkollektivEasyCredit
      - ./tools:/tools
      - ./thirdparty:/shopware/engine/Shopware/Plugins/Community/Frontend
      - /opt/gocode/bin/mhsendmail:/usr/local/bin/mhsendmail
      - /opt/global/conf/mailhog.ini:/usr/local/etc/php/conf.d/mailhog.ini
      - /opt/global/conf/mailhog.ini:/etc/php/7.3/apache2/conf.d/50-mailhog.ini

    environment:
      SMTP_HOST: smtp
      SWDB_DATABASE: shopware
      SWDB_USER: root
      SWDB_PASSWORD: 123456
    labels:
      - "traefik.enable=true"
      - "traefik.web.backend=web"
      - "traefik.web.protocol=http"
      - "traefik.web.headers.forceSTSHeader=true"
      - "traefik.docker.network=web"
    networks:
      - web
      - default
